output "vpc_no" {
  description = "Created VPC number."
  value       = ncloud_vpc.main.id
}

output "subnet_no" {
  description = "Created public subnet number."
  value       = ncloud_subnet.public.id
}

output "server_instance_no" {
  description = "Created Compute server instance number."
  value       = ncloud_server.main.instance_no
}

output "server_private_ip" {
  description = "Private IP assigned to the application server."
  value       = ncloud_server.main.private_ip
}

output "server_public_ip" {
  description = "Public IP assigned to the application server."
  value       = ncloud_public_ip.main.public_ip
}

output "login_key_name" {
  description = "NCloud login key name."
  value       = ncloud_login_key.main.key_name
}

output "login_private_key" {
  description = "Private key generated by NCloud. Store it securely and never commit it."
  value       = ncloud_login_key.main.private_key
  sensitive   = true
}

output "root_password" {
  description = "Temporary NCloud root password retrieved for first-boot recovery."
  value       = data.ncloud_root_password.main.root_password
  sensitive   = true
}
